//! `reclaim` — find and safely reclaim developer disk space.

mod app;
mod cli;
mod commands;
mod render;
mod schedule;
mod tui;

use std::io::IsTerminal;
use std::process::ExitCode;

use anyhow::Result;
use clap::Parser;

use crate::app::{App, Purpose};
use crate::cli::{Cli, Command};
use crate::render::Style;

fn main() -> ExitCode {
    let cli = Cli::parse();
    init_tracing(cli.global.verbose);

    match run(&cli) {
        Ok(code) => ExitCode::from(code),
        Err(error) => {
            // A tool that deletes files must say exactly what went wrong, with
            // the full cause chain rather than just the outermost message.
            eprintln!("error: {error}");
            for cause in error.chain().skip(1) {
                eprintln!("  caused by: {cause}");
            }
            ExitCode::from(2)
        }
    }
}

fn run(cli: &Cli) -> Result<u8> {
    let style = Style::new(cli.global.no_color);

    // Completions are generated by packagers in build sandboxes with no home
    // directory and no config, so they must not require either.
    if let Some(Command::Completions { shell }) = &cli.command {
        use clap::CommandFactory;
        clap_complete::generate(
            *shell,
            &mut Cli::command(),
            "reclaim",
            &mut std::io::stdout(),
        );
        return Ok(0);
    }

    let app = App::new(&cli.global)?;

    let code = match &cli.command {
        Some(Command::Scan(args)) => {
            commands::scan(&app, args, &style)?;
            0
        }
        Some(Command::Clean(args)) => commands::clean(&app, args, &style)? as u8,
        Some(Command::History(args)) => {
            commands::history(&app, args, &style)?;
            0
        }
        Some(Command::Config { action }) => {
            commands::config(&app, action, &style)?;
            0
        }
        Some(Command::Providers) => {
            commands::providers(&app, &style)?;
            0
        }
        Some(Command::Completions { shell }) => {
            use clap::CommandFactory;
            clap_complete::generate(
                *shell,
                &mut Cli::command(),
                "reclaim",
                &mut std::io::stdout(),
            );
            0
        }
        Some(Command::Schedule { action }) => schedule::dispatch(&app, action, &style)?,
        Some(Command::Ui(args)) => {
            reclaim_web::serve(
                app.paths.clone(),
                app.config.clone(),
                reclaim_web::ServeOptions {
                    port: args.port.unwrap_or(app.config.ui.port),
                    open_browser: !args.no_open && app.config.ui.open_browser,
                    dev: args.dev,
                },
            )?;
            0
        }
        None => {
            // Bare `reclaim` is the interactive UI, but only when there is a
            // terminal to draw on. Piped or redirected, fall back to a plain scan
            // so `reclaim | grep` does something sensible instead of failing.
            if std::io::stdout().is_terminal() {
                let filter = app.filter(&cli::FilterArgs::default(), Purpose::Report)?;
                tui::run(&app, filter)?;
            } else {
                commands::scan(&app, &default_scan_args(), &style)?;
            }
            0
        }
    };

    Ok(code)
}

fn default_scan_args() -> cli::ScanArgs {
    cli::ScanArgs {
        filter: cli::FilterArgs::default(),
        json: false,
        all: false,
    }
}

fn init_tracing(verbosity: u8) {
    let level = match verbosity {
        0 => "warn",
        1 => "info",
        2 => "debug",
        _ => "trace",
    };
    let filter = tracing_subscriber::EnvFilter::try_from_env("RECLAIM_LOG")
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new(format!("reclaim={level}")));

    let _ = tracing_subscriber::fmt()
        .with_env_filter(filter)
        .with_writer(std::io::stderr)
        .with_target(false)
        .try_init();
}
